---
linters:
  BorderZero:
    enabled: true
  ColorKeyword:
    enabled: true
  ColorVariable:
    enabled: false
  Comment:
    enabled: true
  DeclarationOrder:
    enabled: true
  DuplicateProperty:
    enabled: true
  ElsePlacement:
    enabled: true
  EmptyRule:
    enabled: true
  EmptyLineBetweenBlocks:
    enabled: true
  HexNotation:
    enabled: true
  IdSelector:
    enabled: true
  ImportantRule:
    enabled: false
  ImportPath:
    enabled: true
  Indentation:
    enabled: true
    character: tab
    width: 1
  LeadingZero:
    enabled: false
  MergeableSelector:
    enabled: true
  NameFormat:
    enabled: true
  NestingDepth:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  PropertyCount:
    enabled: true
  PropertySortOrder:
    enabled: true
    order: smacss
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: true
    max_depth: 3
  SelectorFormat:
    enabled: false
  Shorthand:
    enabled: true
  SingleLinePerProperty:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  SpaceAfterComma:
    enabled: false
  SpaceAfterPropertyColon:
    enabled: true
  SpaceBeforeBrace:
    enabled: false
  SpaceBetweenParens:
    enabled: true
  StringQuotes:
    enabled: true
  TrailingSemicolon:
    enabled: false
  UnnecessaryMantissa:
    enabled: true
  UrlQuotes:
    enabled: true
  VendorPrefix:
    enabled: false
  ZeroUnit:
    enabled: true
