source 'https://rubygems.org'

gem 'roda'
gem 'unicorn'
gem 'pry'
gem 'rake'
gem 'rack-unreloader', require: 'rack/unreloader'
gem 'racksh'
gem 'ansi'
gem 'cae-logger', github: 'celsworth/cae-logger', require: 'cae/logger'
gem 'better_errors'
gem 'binding_of_caller'
gem 'sequel'
gem 'pg'
gem 'sequel_pg', require: 'sequel'
gem 'bcrypt'
gem 'rack_csrf'
gem 'kramdown'
gem 'dalli'
gem 'haml'
gem 'sass'
gem 'coderay'
gem 'scss-lint'
